### PR TITLE
Explain why installments are unavailable with pay what you want

### PR DESCRIPTION
**Pull request by gumclaw**
# Explain why installments are unavailable with pay what you want

## What

When the installments switch is disabled because pay what you want is on, the editor now says why:

- `InstallmentPlanEditor` renders `Installments aren't available with pay what you want.` under the toggle, only for the pay-what-you-want reason. The switch's disabled condition (`totalAmountCents <= 0 || isPWYW`) is unchanged, and no other editor state changes.
- `ToggleSettingRow` takes an optional `describedById` and forwards it as `aria-describedby` on the switch, so the reason is announced and not just painted (Greptile P2 on the first push).

## Why

Tastelint caught this on antiwork/gumroad#7620, which merged before the finding could be answered: with pay what you want on, a seller sees the installments toggle faded out with no explanation, so a rule reads as a bug. #7620 removed exactly this pattern from the pay-what-you-want toggle, whose old message explained itself.

The shape matters here: #7620 is what makes pay what you want reachable on a $0-base product that has a paid version, so this silent disable is newly reachable for that shape. Turning it on also clears `allow_installment_plan` through the editor's existing effect — pre-existing behaviour for any pay-what-you-want product, not introduced by #7620, and not changed here.

## Before / after

Same seeded $0-base product on both legs (`demo`, one free and one priced version), same click-path: pay what you want flipped on and saved through the editor. Before leg is a preview serving `14fb93b38a` (current main, i.e. #7620 without this diff); after leg is this branch at `5aa3420a7a`. Both hosts verified serving that revision via `x-revision`.

Before — the switch is on, installments are faded out, and nothing says why:

Before — pay what you want on, installments faded out with no reason given

After — the same state, with the reason under the row:

After — the same state with the reason under the row

## Checklist

- [x] Scope — the disabled installments toggle now carries its reason, visually and to assistive tech. Not in scope: the `totalAmountCents <= 0` leg of the disable condition (transient in the editor, and the pay-what-you-want alert already covers the free-product case) and the installments-cleared-on-PWYW behaviour.
- [x] Design — house `FieldsetDescription` under the `ToggleSettingRow`, plus `aria-describedby` following `CustomPermalinkInput`. Rejected: a tooltip on a disabled control (invisible to keyboard focus, and a disabled `input` does not take hover reliably).
- [x] Build — `5aa3420a7a` on `gumclaw/gp2573-installments-pwyw-note`
- [x] QA — both legs captured on preview apps at the revisions named above; DOM-level assertions in the QA section.
- [ ] Shipped
- [ ] Market — n/a
- [ ] Sell — n/a

## Tests

```text
./node_modules/.bin/vitest run app/javascript/components/ProductEdit/ProductTab/PriceEditor.test.tsx   # at 5aa3420a7a
Test Files  1 passed (1)
     Tests  7 passed (7)
prettier --check, eslint (DISABLE_TYPE_CHECKED=1), tsc --noEmit: clean
```

Two new examples: the note and the disabled switch with `aria-describedby` pointing at it when pay what you want is on, and neither with the switch enabled when it is off. Mutation-checked — deleting the note fails the first example and nothing else.

CI runs no vitest, so those examples are the local run at this head. `bin/branch-specs` escalates on `SettingRow.tsx` ("no specs were selected for it — mapping gap"), so this PR carries `run-all-specs` and the full Fast/Slow suite ran on `5aa3420a7a`.

## QA

Preview apps, desktop light theme, seeded `demo` in each app's own database ($0 base, `Free Version` $0, `Full Version` $10).

| leg | host | revision | pay what you want on | installments switch | note in the DOM |
| --- | --- | --- | --- | --- | --- |
| before | `gumclaw-gp2573-installments-note.apps.staging.gumroad.org` | `14fb93b38a` | saved through the editor | `disabled=true` | none; `aria-describedby` null |
| after | `gumclaw-gp2573-installments-pwyw.apps.staging.gumroad.org` | `5aa3420a7a` | saved through the editor | `disabled=true` | `Installments aren't available with pay what you want.`; `aria-describedby` equals the note's id |

Read back from each app's database after the save: `permalink=demo price=0 pwyw=true variants=[["Free Version", 0], ["Full Version", 1000]]` on both legs, so the pair differs only in the served code.

Limitations: light desktop only (the note is static type in an existing row; no responsive rule was added); dark and 375px were not captured.

Premerge review: clean @ 5aa3420a7afe60130be48e9740515fc0c1548c4b
Handoff: ready for @gianfrancopiana — the copy and the `ToggleSettingRow` prop are the product-editor surface.

---

AI disclosure: DeepSeek V4.1 Flash (`deepseek/deepseek-v4.1-flash` via OpenRouter) in an autonomous Hermes Agent session, from a tastelint finding on antiwork/gumroad#7620. Prompts given: verify the finding against the live code, fix it the way tastelint described, fix the Greptile P2 honestly or reject it with reasons, and capture before/after evidence.

### CODE REVIEW

File: app/javascript/components/ProductEdit/ProductTab/InstallmentPlanEditor.tsx [hunk 1]
```diff
@@ -37,23 +37,28 @@ export const InstallmentPlanEditor = ({
...
+                  <Input {...props} type="number" min={2} aria-label="Number of installments" />
+                  <Label>equal monthly payments</Label>
+                </InputGroup>
+              )}
+            </NumberInput>
+          </Fieldset>
+        }
+      />
+      {isPWYW ? (
+        <FieldsetDescription>Installments aren&apos;t available with pay what you want.</FieldsetDescription>
```
[the remark this answers is not in the document]
Comment (gumclaw) [reply app/javascript/components/ProductEdit/ProductTab/InstallmentPlanEditor.tsx]: Fixed in 5aa3420a7a. `ToggleSettingRow` forwards an optional `describedById` to the switch, and the note carries the matching id, so the disabled switch announces its reason — same wiring as `CustomPermalinkInput`. The spec pins it: `aria-describedby` equals the note's id when pay what you want is on, and is absent when it is off.
